apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cogniflow.fullname" . }}-orchestrator
  labels:
    {{- include "cogniflow.orchestrator.labels" . | nindent 4 }}
spec:
  {{- if not .Values.orchestrator.autoscaling.enabled }}
  replicas: {{ .Values.orchestrator.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "cogniflow.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: orchestrator
  template:
    metadata:
      labels:
        {{- include "cogniflow.orchestrator.labels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cogniflow.fullname" . }}-sa
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: orchestrator
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}/orchestrator:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.orchestrator.port }}
              protocol: TCP
          envFrom:
            - secretRef:
                name: {{ include "cogniflow.fullname" . }}-secrets
          env:
            {{- range $key, $val := .Values.orchestrator.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
            - name: ORCH_PORT
              value: {{ .Values.orchestrator.port | quote }}
          livenessProbe:
            {{- toYaml .Values.orchestrator.probes.liveness | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.orchestrator.probes.readiness | nindent 12 }}
          resources:
            {{- toYaml .Values.orchestrator.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          volumeMounts:
            {{- if .Values.persistence.enabled }}
            - name: data
              mountPath: /data
            {{- end }}
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
        {{- if .Values.persistence.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "cogniflow.fullname" . }}-data
        {{- end }}
