apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cogniflow.fullname" . }}-secrets
  labels:
    {{- include "cogniflow.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.openaiApiKey }}
  OPENAI_API_KEY: {{ .Values.secrets.openaiApiKey | quote }}
  {{- end }}
  {{- if .Values.secrets.anthropicApiKey }}
  ANTHROPIC_API_KEY: {{ .Values.secrets.anthropicApiKey | quote }}
  {{- end }}
  {{- if .Values.secrets.mistralApiKey }}
  MISTRAL_API_KEY: {{ .Values.secrets.mistralApiKey | quote }}
  {{- end }}
  {{- if .Values.secrets.hfApiKey }}
  HF_API_KEY: {{ .Values.secrets.hfApiKey | quote }}
  {{- end }}
  {{- if .Values.secrets.ollamaBaseUrl }}
  OLLAMA_BASE_URL: {{ .Values.secrets.ollamaBaseUrl | quote }}
  {{- end }}
  {{- if .Values.secrets.groqApiKey }}
  GROQ_API_KEY: {{ .Values.secrets.groqApiKey | quote }}
  {{- end }}
  {{- if .Values.secrets.stripeApiKey }}
  STRIPE_API_KEY: {{ .Values.secrets.stripeApiKey | quote }}
  {{- end }}
  {{- if .Values.secrets.stripeMeterId }}
  STRIPE_METER_ID: {{ .Values.secrets.stripeMeterId | quote }}
  {{- end }}
